spring:
  application:
    name: codyweb-gateway
  ## API SECURITY WITH KEYCLOAK PROVIDER
  security:
    oauth2:
      client:
        provider:
          keycloak:
#            issuer-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            user-info-authentication-method: header
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          spring-cloud-gateway-client:
            authorization-grant-type: authorization_code
            client-id: codyweb-client
            client-secret: d9c36075-3519-4a42-a198-f53dbc566ede
            provider: keycloak
            redirect-uri: http://localhost:8082/login/oauth2/code/codyweb-client
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

  ## GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      default-filters: TokenRelay
      discovery:
        locator:          lower-case-service-id: true
      routes:
        ## USER SERVICE
        - id: codyweb-user-service
          uri: lb://codyweb-user-service
          predicates:
            - Path=/api/v1/user/**
#          filters:
#            - StripPrefix=1


## SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://localhost:8089/auth
      realm: codyweb

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG