spring:
  application:
    name: codyweb-content-service
  datasource:
    url: jdbc:postgresql://localhost:5432/post
    username: postgres
    password: cody3399
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/auth/realms/codyweb
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8089/auth
      realm: codyweb
      clientId: codyweb-client
      client-secret: d9c36075-3519-4a42-a198-f53dbc566ede

  
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG