spring:
  application:
    name: codyweb-user-service
   
  rabbitmq:
    host: localhost
    port: 5672
    username: guest     password: guest
    
   
  datasource:
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
    
  cloud:
    loadbalancer:      ribbon:
        enabled: false
  
  security:    oauth2:      resourceserver:        jwt:          issuer-uri: http://localhost:8089/auth/realms/codyweb

    
server:
  port: 8083


info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8089/auth
      realm: codyweb
      clientId: codyweb-client
      client-secret: d9c36075-3519-4a42-a198-f53dbc566ede

cody:
  app:
    jwtSecret: secret
    jwtExpirationMs: 2000
    base.url: http://localhost:8082
    verification.token.validity: 5000

 
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG