spring:
  application:
    name: codyweb-user-service
   
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
   
  datasource:
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  security:    oauth2:      resourceserver:        jwt:          issuer-uri: http://localhost:8089/auth/realms/codyweb
  cloud:
    vault:
      host: localhost
      port: 8288
      scheme: http
      authentication: TOKEN
      token: s.1eJL6HWOX3kUe4c38z9ZjDQB
      application-name: user-service
      
  
  
server:
  port: 8083

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8089/auth
      realm: codyweb
      clientId: codyweb-client
      client-secret: d9c36075-3519-4a42-a198-f53dbc566ede

cody:
  app:
    jwtSecret: secret
    jwtExpirationMs: 2000
    base.url: http://localhost:8082
    verification.token.validity: 5000

 
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG